image: /home/spark/spark_noetic_team17/Robot_manipulation/src/team17/auto_match_24/auto_match/scripts/../config/test_map.pgm
resolution: 0.050000
origin: [-10.000000, -10.000000, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

